name: 'Harbor Scan Report'
description: 'Publish a Harbor image vulnerability scan report to PR comment'
inputs:
  harbor-host:
    description: 'Hostname of your Harbor instance (without protocol).'
    required: true
  harbor-robot:
    description: 'Robot or Username to access Harbor with.'
    required: true
  harbor-token:
    description: "Robot's Token (or Username's password)"
    required: true
  image:
    description: 'Image to scan (project/repo:tag)'
    required: true
  github-url:
    description: '${{ github.event.issue.comments_url }} - for issue, ${{ github.event.pull_request.comments_url }} - for PR'
    required: false
  github-token:
    description: 'A GitHub personal access token used to commit to a branch on your behalf.'
    required: false
  harbor-proto:
    description: 'Protocol of Harbor instance. Use it, if your Harbor uses http'
    required: false
    default: 'https'
  harbor-port:
    description: 'Custom port of Harbor instance. Use it, if Harbor instance has custom port'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.harbor-host }}
    - ${{ inputs.harbor-robot }}
    - ${{ inputs.harbor-token }}
    - ${{ inputs.image }}
    - ${{ inputs.github-url }}
    - ${{ inputs.github-token }}
    - ${{ inputs.harbor-proto }}
    - ${{ inputs.harbor-port }}
