name: "Build Tag"

on:
  push:
    tags:
      - '*'

jobs:
  docker-image:
    name: Build Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Latest Tag
        id: get_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1.1

      - name: Login to kio.ee
        run: echo "${{ secrets.HARBOR_TOKEN }}" | docker login --username ${{ secrets.HARBOR_ROBOT }} --password-stdin kio.ee

      - name: Build and push
        run: docker build -t kio.ee/kyberorg/hsr:${{ steps.get_tag.outputs.tag }} . && docker push kio.ee/kyberorg/hsr:${{ steps.get_tag.outputs.tag }}
      - name: Logout
        run: docker logout kio.ee
