name: "Build Trunk"

on:
  push:
    branches:
      - trunk

jobs:
  docker-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to kio.ee
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HARBOR_ROBOT }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kio.ee/kyberorg/hsr:trunk

  scan-image:
    name: Scan Image
    needs: docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Run Report
        uses: kyberorg/harbor-scan-report@trunk
        with:
          harbor-host: kio.ee
          harbor-robot: ${{ secrets.HARBOR_ROBOT }}
          harbor-token: ${{ secrets.HARBOR_TOKEN }}
          image: kio.ee/kyberorg/hsr:trunk
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-allowed-severity: high
