name: "Test This Workflow"

on:
  pull_request:
    branches: [ trunk ]
  push:
  workflow_dispatch:

jobs:
  harbor-scan-report:
    name: Harbor Image Scan Report
    runs-on: ubuntu-latest

    steps:
      - name: Run Report
        uses: kyberorg/harbor-scan-report@poc
        with:
          harbor-host: kio.ee
          harbor-robot: ${{ secrets.HARBOR_ROBOT }}
          harbor-token: ${{ secrets.HARBOR_TOKEN }}
          image: hub/library/nginx:1.23.1
          github-url: ${{ github.event.issue.comments_url }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
